title: LumenaAutomation
url: https://lumenaautomation.co.in
baseurl: ""
lang: en
markdown: kramdown
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - scripts
  - work
  - '*.py'
